---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/14rcole-rhtap/infra-deployments
- op: replace
  path: /spec/source/targetRevision
  value: preview-integration-team-delete-snapshots
