---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/14rcole/infra-deployments
- op: replace
  path: /spec/source/targetRevision
  value: preview-preview-preview-preview-preview-main
