resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/14rcole/application-api/config/crd?ref=spec-application-optional


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
